version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app_web
      MYSQL_PASSWORD: app_password
  web:
    depends_on:
      - db
    build: .
    container_name: app
    image: app:latest
    volumes: 
      - ./:/var/www/html/public
    ports:
     - "8888:80"
volumes:
  db_data: {}
